apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: budgeting-app
spec:
  type: LoadBalancer
  selector:
    app: budgeting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
